/**
 * Persistent local storage, namespaced per account.
 *
 * `react-native-mmkv` has been in the dependency list since the demo and
 * imported nowhere. It gets a real job here.
 *
 * **Per-account namespacing is a requirement, not a tidiness choice**
 * (TRD-AUTH-008). Phones are shared: a student borrows a sibling's device, two
 * classmates use one handset. Their outboxes, caches, and resume state must
 * never merge, and signing out must not destroy the other account's unsynced
 * work.
 */

import { MMKV } from 'react-native-mmkv';

/** Never namespaced — it is what tells us which account is active. */
const rootStore = new MMKV({ id: 'lenterra.root' });

const accountStores = new Map<string, MMKV>();

export const ROOT_KEYS = {
  activeAccountId: 'active-account-id',
  knownAccountIds: 'known-account-ids',
  deviceId: 'device-id',
  /** Server time minus device time, in ms. Corrects offline event ordering. */
  clockSkewMs: 'clock-skew-ms',
} as const;

export const ACCOUNT_KEYS = {
  session: 'session',
  outbox: 'outbox',
  deviceSeq: 'device-seq',
  catalogVersion: 'catalog-version',
  catalogPart: 'catalog-part:',
  resume: 'resume',
  settings: 'settings',
  queryCache: 'query-cache',
  lastSyncAt: 'last-sync-at',
  /**
   * What a teacher has assigned, as of the last pull.
   *
   * Cached rather than fetched on demand because it has to be readable on the
   * bus home. A student who is told what to do next only while they have signal
   * is being told at the one moment they cannot act on it.
   */
  assignments: 'assignments',
} as const;

export function rootStorage(): MMKV {
  return rootStore;
}

/**
 * Storage for one account.
 *
 * The id is part of the MMKV instance id, so two accounts cannot see each
 * other's keys even by mistake — the isolation is at the file level rather
 * than enforced by a key prefix somebody might forget.
 */
export function accountStorage(accountId: string): MMKV {
  let store = accountStores.get(accountId);
  if (!store) {
    store = new MMKV({ id: `lenterra.account.${accountId}` });
    accountStores.set(accountId, store);
  }
  return store;
}

export function activeAccountId(): string | null {
  return rootStore.getString(ROOT_KEYS.activeAccountId) ?? null;
}

export function setActiveAccount(accountId: string): void {
  rootStore.set(ROOT_KEYS.activeAccountId, accountId);

  const known = knownAccountIds();
  if (!known.includes(accountId)) {
    rootStore.set(ROOT_KEYS.knownAccountIds, JSON.stringify([...known, accountId]));
  }
}

export function knownAccountIds(): string[] {
  const raw = rootStore.getString(ROOT_KEYS.knownAccountIds);
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as string[]) : [];
  } catch {
    return [];
  }
}

/**
 * Sign out.
 *
 * Clears the session token and the active-account pointer, and **keeps the
 * outbox**. A student who signs out on a borrowed phone before their work has
 * synced has not agreed to lose it (PRD-ONB-015).
 */
export function signOut(accountId: string): void {
  accountStorage(accountId).delete(ACCOUNT_KEYS.session);
  rootStore.delete(ROOT_KEYS.activeAccountId);
}

/** Full removal, for an account deletion or a device handover. */
export function forgetAccount(accountId: string): void {
  accountStorage(accountId).clearAll();
  accountStores.delete(accountId);
  rootStore.set(
    ROOT_KEYS.knownAccountIds,
    JSON.stringify(knownAccountIds().filter((id) => id !== accountId)),
  );
  if (activeAccountId() === accountId) rootStore.delete(ROOT_KEYS.activeAccountId);
}

// ---------------------------------------------------------------------------
// Typed helpers
// ---------------------------------------------------------------------------

export function readJson<T>(store: MMKV, key: string): T | null {
  const raw = store.getString(key);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as T;
  } catch {
    // Corrupt storage is recoverable — every persisted value here is a cache
    // or a queue that can be rebuilt. Crashing on it would not be.
    store.delete(key);
    return null;
  }
}

export function writeJson(store: MMKV, key: string, value: unknown): void {
  store.set(key, JSON.stringify(value));
}

/**
 * A stable per-install identifier.
 *
 * Used only to rate-limit class-code attempts before an account exists. It is
 * not an advertising identifier, is never sent with learning data, and is
 * regenerated by a reinstall.
 */
export function deviceId(): string {
  let id = rootStore.getString(ROOT_KEYS.deviceId);
  if (!id) {
    id = `dev-${Math.random().toString(36).slice(2)}-${Date.now().toString(36)}`;
    rootStore.set(ROOT_KEYS.deviceId, id);
  }
  return id;
}

/**
 * Next monotonic sequence number for this account on this device.
 *
 * Orders an offline batch on the server. It has to be monotonic per device
 * rather than a timestamp, because device clocks are wrong often enough that
 * ordering by them reorders a student's own history (20-09).
 */
export function nextDeviceSeq(accountId: string): number {
  const store = accountStorage(accountId);
  const next = (store.getNumber(ACCOUNT_KEYS.deviceSeq) ?? 0) + 1;
  store.set(ACCOUNT_KEYS.deviceSeq, next);
  return next;
}
